# Generated by Django 4.0.6 on 2022-08-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='createdOn',
            field=models.DateTimeField(),
        ),
    ]
