# Generated by Django 4.0.6 on 2022-08-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listings_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listing'),
        ),
    ]
