# Generated by Django 4.0.6 on 2022-08-04 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listings_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchList',
            field=models.ManyToManyField(related_name='watchList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
