# Generated by Django 4.0.6 on 2022-08-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listings_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
        ),
    ]
